### ISSUE TITLE
Use Celsius instead of Fahrenheit

### ISSUE THREAD

**Issue by la3mmchen** [alex-konshin/f007th-rpi#1]
Hi,

i'm using your tool for collecting and sending to InfluxDb.
Can you provide me with a hint how to convert the values into Celsius before they are send to Influx?

I already found the decoded value in ReceivedMessage.hpp:114. I just converted it to Celsius: 
`
  static int getTemperatureF007TH(uint32_t nF007TH) {
    return (((((nF007TH>>8)&4095)-400)/10)-32)*5/9;
  }
  int getTemperatureF007TH() {
    return data == __null ? -4597 : (((((data->nF007TH>>8)&4095)-400)/10)-32)*5/9;
  }
` 

In f007th_send.cpp you'll divide the value by 10 or insert a dot so that Influx gets Fahrenheit instead of deciFahrenheit.
As I'm not a C++ Dev I'm unable to find the right place to tweak. 
Can you provide me with a hint? 

Bonus question: Obviously the best solution would be to provide a start parameter to switch between Celsius and Fahrenheit ;-)

Bye,
Alex

**Comment by alex-konshin** [comment]
I will provide an option but I will do it during weekend.
Unfortunately I have to many ideas and too little free time :).
Thank you for your feedback. Спасибо.

**Comment by alex-konshin** [comment]
Done.
Added option -C  (as well as option -U) to command f007th_send.
Also added opened a capability to print received data to stdout.

**Comment by la3mmchen** [comment]
Great, Thanks a lot! ;)
